language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - go test ./...
  - go get ./...
  - go build -o ./product-catalog-import-tool
